#!/usr/bin/env bash
# Install / bootstrap for the eGerak v2 Cloud Agent environment.
# Idempotent: installs system Postgres, prepares a local dev database, installs
# Node dependencies, syncs the Drizzle schema, and seeds baseline data.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"
APP_DIR="${REPO_ROOT}/egerak-v2"

# 1. System dependency: PostgreSQL server (skip if already present).
if ! ls /usr/lib/postgresql/*/bin/initdb >/dev/null 2>&1; then
  echo "Installing PostgreSQL"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# 2. Bring up the local database cluster (idempotent).
bash "${SCRIPT_DIR}/start.sh"

# 3. Node dependencies.
cd "${APP_DIR}"
npm ci

# 4. Local dev env file (never committed; local Postgres + random secret).
if [ ! -f .env.local ]; then
  echo "Writing egerak-v2/.env.local for local development"
  AUTH_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
  cat > .env.local <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
# Local Postgres and a local-only secret — NOT production values.
DATABASE_URL=postgres://$(id -un)@127.0.0.1:5432/egerak
AUTH_SECRET=${AUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000

SEED_ADMIN_USERNAME=admin
SEED_ADMIN_PASSWORD=AdminMasuk!2026
SEED_ADMIN_NAMA=Pentadbir Sistem
SEED_ADMIN_JAWATAN=PEGAWAI USTP
SEED_ADMIN_SEKTOR_CODE=USTP

# OPR AI (optional): set keys to enable draft generation.
GROQ_API_KEY=
GROQ_MODEL=openai/gpt-oss-120b
GEMINI_API_KEY=
GEMINI_MODEL=gemini-2.5-flash

# OPR photo storage (optional): configure GAS to enable uploads.
OPR_PHOTO_STORAGE=gas
GAS_WEB_APP_URL=
GAS_UPLOAD_SECRET=
EOF
fi

# 5. Sync schema to the local DB.
# The Drizzle migration journal (drizzle/meta/_journal.json) only registers
# migrations 0000-0006, so `db:migrate` leaves the DB behind lib/schema.ts.
# `drizzle-kit push` makes the local DB match the app schema and is idempotent.
npx drizzle-kit push --force

# 6. Seed baseline data (sectors, rooms, admin user). The seed script is idempotent.
npm run db:seed

echo "eGerak v2 install complete."
